# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171030_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imglink',
            field=models.URLField(default=''),
        ),
    ]
