# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171031_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='papi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
