# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171105_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='papi',
            new_name='data',
        ),
    ]
