# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171111_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='columns',
            field=models.CharField(default='', max_length=500),
        ),
    ]
