# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
