# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Subject', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
